### ISSUE TITLE
股票摸鱼无效

### ISSUE THREAD

**Issue by supergithuber** [cteamx/Thief-Book#10]
股票摸鱼一直显示NaN,NaN%。
系统：MacOS  Mojave (10.14.4)

**Comment by sanjinhub** [comment]
有网吗？股票代码设置的对嘛？代码格式为 ： sz12312313 这种

**Comment by supergithuber** [comment]
> 有网吗？股票代码设置的对嘛？代码格式为 ： sz12312313 这种

有网，换了好几个wifi；股票代码没错，我还把你readme里的sh600519拿来试，也无效。
是不是股票接口调用有次数限制或者机器限制？

**Comment by sanjinhub** [comment]
@supergithuber 没有任何限制，可以加微信 方便查找问题

**Comment by JIE77777** [comment]
股票摸鱼十分不稳定，sh600519有时可显示，大部分时候不行
