### ISSUE TITLE
由于js bug 导致无法运行，详情附件

### ISSUE THREAD

**Issue by nirvanacc** [cteamx/Thief-Book#11]
rt

![}4R2FM6UZ3MCV) 7DG_ UQM](https://user-images.githubusercontent.com/36750055/64404372-4ad6f880-d0ae-11e9-993c-06a1f2d3b297.png)

![7NJ`S8GLQQ5HEVU12PWK(4P](https://user-images.githubusercontent.com/36750055/64404378-50344300-d0ae-11e9-84f6-ac1e108f8128.png)

**Comment by sanjinhub** [comment]
快捷键设置错误，看文档 里面有说明
