### ISSUE TITLE
win版可能需要一个窗口置顶功能

### ISSUE THREAD

**Issue by ncrovi** [cteamx/Thief-Book#16]
没有办法快速把窗口带到最前，因为他不会出现在任务栏和Alt+Tab中

**Comment by ncrovi** [comment]
第二次打开后，内容区域显示今日开机时长后就正常置顶了。
第一次安装完成直接打开，内容区域没有东西时没有置顶

**Comment by sanjinhub** [comment]
置顶 win 的问题，重启即可
