### ISSUE TITLE
mac版本的thief_data.json文件在哪里啊

### ISSUE THREAD

**Issue by luohengyi** [cteamx/Thief-Book#2]

**Comment by huowenxuan** [comment]
同问

**Comment by luohengyi** [comment]
/Library/Application Support 目录下去找找

**Comment by huowenxuan** [comment]
没有，只有这么几个

/Library/Application Support  > ls
Adobe
App Store
Apple
ApplePushService
CrashReporter
GarageBand
Huamaojiasu
Macromedia
Microsoft
Nemu
Oracle
ProApps
Script Editor
ShadowsocksX
Unity
VirtualBox
Wireshark
com.apple.TCC
iLifeMediaBrowser
org.pqrs

**Comment by luohengyi** [comment]
在/Users/luohengyi/Library/Application Support下说错了嘿嘿

**Comment by luohengyi** [comment]
换成你的用户目录

**Comment by huowenxuan** [comment]
找到了嘿嘿，摸🐟愉快🤝

**Comment by luohengyi** [comment]
感觉不是很好用，已经在自己写了，mac的快捷不好使

**Comment by sanjinhub** [comment]
@luohengyi @huowenxuan 

open -e ~/Library/Application\ Support/thief-book/thief_data.json 修改 or 删掉

最近在更新功能，忙的忘记看了。

@luohengyi 欢迎自己写！

**Comment by luohengyi** [comment]
躲懒，在网上找到了个idea插件 TextReader 比较不错 @sanjinhub 你可以参考下哈哈

**Comment by luohengyi** [comment]
@sanjinhub 主要是翻页不好使，要是能滑动鼠标滚轮翻页就很完美了

**Comment by sanjinhub** [comment]
@luohengyi 不好使请提BUG，说出问题。经过多名用户的调研，大家更喜欢鼠标按键！
