### ISSUE TITLE
请问是否考虑加入总在最前面的功能呢？

### ISSUE THREAD

**Issue by LevineWoo** [cteamx/Thief-Book#21]
每次要看股票的报价需要显示桌面，再点一个东西出来才能看得到。

**Comment by sanjinhub** [comment]
目前就是最前的，但是WIN会出现不兼容的情况，这个问题在研究解决

**Comment by LevineWoo** [comment]
> 目前就是最前的，但是WIN会出现不兼容的情况，这个问题在研究解决

试了下，使用管理员权限运行就可以了。
