### ISSUE TITLE
手贱发现个bug

### ISSUE THREAD

**Issue by cskami** [cteamx/Thief-Book#23]
win10快捷键设置Shift + Space 点保存直接报错秒退了，再开也还是报错，配置不知道存在哪里😂

**Comment by cskami** [comment]
还有能不能不要快捷键，单字母翻页和单字母老板键可以吗，不然按久了手好酸啊

**Comment by cskami** [comment]
配置已经找到了，快捷键+空格会有问题，改掉就好了

**Comment by sanjinhub** [comment]
感谢反馈，我记得去掉了空格键了。

**Comment by Chris-0-0** [comment]
配置在什么位置?

**Comment by Chris-0-0** [comment]
配置在什么位置? @cskami

**Comment by cskami** [comment]
C:\Users\你的用户名\AppData\Roaming\thief-book的thief_data.json文件@Chris-0-0
