### ISSUE TITLE
自动翻页不清楚。。。。

### ISSUE THREAD

**Issue by c2ch** [cteamx/Thief-Book#24]

**Comment by c2ch** [comment]
![image](https://user-images.githubusercontent.com/35028011/67838829-343ca300-fb2d-11e9-968a-b983af24e036.png)
不清楚，有时候上一页的还没完全清除，下一页出来了，有点 不清楚。。。翻页间隔是5s

**Comment by sanjinhub** [comment]
这是 完全透明的bug,建议 半透明 or 调整背景色
