### ISSUE TITLE
快捷键设置错误后崩溃

### ISSUE THREAD

**Issue by XQSNOW** [cteamx/Thief-Book#4]
快捷键设置错误后崩溃。无法改回默认快捷键。建议添加合法性检查和错误自动恢复功能。

**Comment by sanjinhub** [comment]
看文档异常汇总，这个问题下个版本会解决

**Comment by kilige** [comment]
我的崩溃后就再也打不开了，用的压缩版，删除重新解压出来也一样，重启也是一样，一直崩溃

**Comment by 303023604** [comment]
重新安装也没用  有好的解决办法吗
