### ISSUE TITLE
设置快捷键错误，请看文档异常汇总！

### ISSUE THREAD

**Issue by emtry** [cteamx/Thief-Book#43]
OSX 10.15.2
如何恢复默认设置

**Comment by sanjinhub** [comment]
看文档 异常汇总

**Comment by MonkeyCoder128** [comment]
设置完点击保存之后软件推出,重新启动指挥闪过一个对话框提示快捷键异常就没有然后了
![Snipaste_2020-01-13_15-43-17](https://user-images.githubusercontent.com/42332199/72239275-726d3d00-361b-11ea-8cb1-4ea2e9405542.png)

**Comment by emtry** [comment]
现在是打不开设置，只提示了 设置快捷键错误，请看文档异常汇总！ 就没任何反应了

**Comment by emtry** [comment]
/Users/xxxxx/Library/Application Support/thief-book/thief_data.json
