### ISSUE TITLE
请问3.2版本linux的有没有文档操作？

### ISSUE THREAD

**Issue by Suvigo** [cteamx/Thief-Book#63]
我下载了appimage, 打开之后只有一个显示条，并没有设置页面，快捷键可以用，但是没有看到设置页面。

请问我应该怎么配置呢？

**Comment by Suvigo** [comment]
sorry , 不好意思看错了...找到配置项了

**Comment by HermanZYZ** [comment]
> sorry , 不好意思看错了...找到配置项了

请问你是在哪里找到的呢？我也出现同样的情况

**Comment by Suvigo** [comment]
首先你是直接chmod appimage 然后shell执行的嘛？这样执行不行
通过linux桌面版把Appimage文件的权限，右键文件 –> 属性 –> 权限 –> 允许作为程序执行文件，然后右键打开之后，右上角会有一个黑帽子的图标，然后有个显示条，黑帽子图标右键就有设置页面了

**Comment by HermanZYZ** [comment]
> 首先你是直接chmod appimage 然后shell执行的嘛？这样执行不行
> 通过linux桌面版把Appimage文件的权限，右键文件 –> 属性 –> 权限 –> 允许作为程序执行文件，然后右键打开之后，右上角会有一个黑帽子的图标，然后有个显示条，黑帽子图标右键就有设置页面了

我的这样子做也没用，不过我的是4.0.0版本的，谢谢！

**Comment by Suvigo** [comment]
您客气了，我后来其实不用这么操作了，vscode还是比较简便的....

**Comment by HermanZYZ** [comment]
> 您客气了，我后来其实不用这么操作了，vscode还是比较简便的....

vscode里面怎么用？可否详细指导一下？

**Comment by Suvigo** [comment]
vscode里面ctrl shift p打开安装扩展，然后搜索thief就有，直接安装之后就可以使用，点击齿轮有个扩展设置，就有设置页面，然后按照文档设置即可，下面的bar里面就会有相应的摸鱼信息....我之前一直拿他看股票，大概能支持7支股票同时显示

**Comment by HermanZYZ** [comment]
> vscode里面ctrl shift p打开安装扩展，然后搜索thief就有，直接安装之后就可以使用，点击齿轮有个扩展设置，就有设置页面，然后按照文档设置即可，下面的bar里面就会有相应的摸鱼信息....我之前一直拿他看股票，大概能支持7支股票同时显示

感谢！同道中人，这两天辛苦了！

**Comment by Suvigo** [comment]
没事没事，摸鱼快乐~

**Comment by HermanZYZ** [comment]
> vscode里面ctrl shift p打开安装扩展，然后搜索thief就有，直接安装之后就可以使用，点击齿轮有个扩展设置，就有设置页面，然后按照文档设置即可，下面的bar里面就会有相应的摸鱼信息....我之前一直拿他看股票，大概能支持7支股票同时显示

欸，我搜了一下，只有thief-book，貌似只能用来看书？

**Comment by Suvigo** [comment]
对，只能看书了。
之前用桌面版的看股票，vscode的看书。。

**Comment by HermanZYZ** [comment]
> 对，只能看书了。
> 之前用桌面版的看股票，vscode的看书。。

好
