### ISSUE TITLE
win10系统1903经常看一会就闪退了

### ISSUE THREAD

**Issue by Angry40** [cteamx/Thief-Book#7]

**Comment by sanjinhub** [comment]
1903 是什么意思？目前自动翻页有闪退问题。等下个版本修复

**Comment by DaduCC** [comment]
我也有同样的问题。win10专业版，版本号1903，操作系统版本号18362.295

**Comment by sanjinhub** [comment]
@DaduCC 自动翻页吗？

**Comment by DaduCC** [comment]
> @DaduCC 自动翻页吗？

不是，快捷键翻页

**Comment by habyss** [comment]
同win10,看一会儿之后会闪退.

**Comment by brebrreier** [comment]
win10，版本号1903，快捷键翻页，一会儿就会闪退，退出软件后重新启动要好几次才能正常运行。

**Comment by sanjinhub** [comment]
奔溃问题已经修复
